---
# Playbook for installation RDMA SHARED HCA DP with CNI's and corresponded prerequisites
# Required installed Kubernetes cluster by Kubespray
# Supported OS for ALL K8s Nodes: ONLY Ubuntu 18.04
# Support K8s v1.16 and later. 
# 
- hosts: all
  become: true
  become_method: sudo
  handlers:
  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami

# Install prerequisites for ALL Nodes
  tasks:
  - name: Install prerequisites for ALL Nodes
    include_role:
      name: mlnx-hca-shared
      tasks_from: allhosts
        

#Apply configuration for K8s cluster via K8s Master Node
- hosts: kube-master
  become: true
  become_method: sudo
  tasks:
  - include_role:
      name: mlnx-hca-shared
      tasks_from: k8smaster


